export enum CreditCardStatementReferencesEnum {
  PAYMENT = 'PAYMENT',
  PAT = 'PAT',
  INSTALLMENT = 'INSTALLMENT',
  CHARGE = 'CHARGE',
  UNBILLED_INSTALLMENT = 'UNBILLED_INSTALLMENT',
  TRANSACTION = 'TRANSACTION',
}
